export interface Product {
  id: string;
  name: string;
  brand: string;
  category: string;
  subcategory?: string;
  price: number;
  discountedPrice: number;
  unit: string;
  image: string;
  rating: number;
  reviews: number;
  inStock: boolean;
  description: string;
  tags: string[];
}

export interface Category {
  id: string;
  name: string;
  emoji: string;
  image?: string;
  description: string;
}

export const CATEGORIES: Category[] = [
  {
    id: 'fruits-vegetables',
    name: 'Vegetables',
    emoji: '🥦',
    image: '/assets/generated/category-fruits.dim_96x96.png',
    description: 'Fresh farm produce'
  },
  {
    id: 'eggs',
    name: 'Eggs',
    emoji: '🥚',
    description: 'Fresh farm eggs'
  },
  {
    id: 'meat',
    name: 'Meat',
    emoji: '🥩',
    description: 'Fresh meat & poultry'
  }
];

export const ALL_PRODUCTS: Product[] = [
  // ─── FRUITS & VEGETABLES ───────────────────────────────────────────────────
  {
    id: 'fv-001',
    name: 'Fresh Tomatoes',
    brand: 'Farm Fresh',
    category: 'fruits-vegetables',
    subcategory: 'vegetables',
    price: 40,
    discountedPrice: 35,
    unit: '500g',
    image: '🍅',
    rating: 4.3,
    reviews: 234,
    inStock: true,
    description: 'Juicy red tomatoes, freshly harvested',
    tags: ['fresh', 'organic', 'vegetables']
  },
  {
    id: 'fv-002',
    name: 'Baby Spinach',
    brand: 'Green Valley',
    category: 'fruits-vegetables',
    subcategory: 'leafy-greens',
    price: 35,
    discountedPrice: 30,
    unit: '200g',
    image: '🥬',
    rating: 4.5,
    reviews: 189,
    inStock: true,
    description: 'Tender baby spinach leaves, washed and ready',
    tags: ['fresh', 'organic', 'leafy-greens']
  },
  {
    id: 'fv-003',
    name: 'Alphonso Mangoes',
    brand: 'Ratnagiri Farms',
    category: 'fruits-vegetables',
    subcategory: 'fruits',
    price: 350,
    discountedPrice: 299,
    unit: '1kg',
    image: '🥭',
    rating: 4.8,
    reviews: 567,
    inStock: true,
    description: 'Premium Alphonso mangoes from Ratnagiri',
    tags: ['seasonal', 'premium', 'fruits']
  },
  {
    id: 'fv-004',
    name: 'Organic Bananas',
    brand: "Nature's Best",
    category: 'fruits-vegetables',
    subcategory: 'fruits',
    price: 60,
    discountedPrice: 55,
    unit: '1 dozen',
    image: '🍌',
    rating: 4.4,
    reviews: 312,
    inStock: true,
    description: 'Organic bananas, naturally ripened',
    tags: ['organic', 'fruits', 'healthy']
  },
  {
    id: 'fv-005',
    name: 'Red Onions',
    brand: 'Farm Fresh',
    category: 'fruits-vegetables',
    subcategory: 'vegetables',
    price: 45,
    discountedPrice: 38,
    unit: '1kg',
    image: '🧅',
    rating: 4.2,
    reviews: 445,
    inStock: true,
    description: 'Fresh red onions, essential for Indian cooking',
    tags: ['fresh', 'vegetables', 'essential']
  },
  {
    id: 'fv-006',
    name: 'Green Capsicum',
    brand: 'Green Valley',
    category: 'fruits-vegetables',
    subcategory: 'vegetables',
    price: 55,
    discountedPrice: 48,
    unit: '500g',
    image: '🫑',
    rating: 4.1,
    reviews: 178,
    inStock: true,
    description: 'Crisp green bell peppers',
    tags: ['fresh', 'vegetables']
  },
  {
    id: 'fv-007',
    name: 'Potatoes',
    brand: 'Farm Fresh',
    category: 'fruits-vegetables',
    subcategory: 'vegetables',
    price: 30,
    discountedPrice: 25,
    unit: '1kg',
    image: '🥔',
    rating: 4.3,
    reviews: 678,
    inStock: true,
    description: 'Fresh potatoes, perfect for all dishes',
    tags: ['fresh', 'vegetables', 'essential']
  },
  {
    id: 'fv-008',
    name: 'Cauliflower',
    brand: 'Green Valley',
    category: 'fruits-vegetables',
    subcategory: 'vegetables',
    price: 40,
    discountedPrice: 35,
    unit: '1 piece',
    image: '🥦',
    rating: 4.0,
    reviews: 234,
    inStock: true,
    description: 'Fresh white cauliflower',
    tags: ['fresh', 'vegetables']
  },
  {
    id: 'fv-009',
    name: 'Strawberries',
    brand: 'Berry Fresh',
    category: 'fruits-vegetables',
    subcategory: 'fruits',
    price: 120,
    discountedPrice: 99,
    unit: '250g',
    image: '🍓',
    rating: 4.6,
    reviews: 345,
    inStock: true,
    description: 'Sweet and juicy strawberries',
    tags: ['seasonal', 'fruits', 'premium']
  },
  {
    id: 'fv-010',
    name: 'Garlic',
    brand: 'Farm Fresh',
    category: 'fruits-vegetables',
    subcategory: 'vegetables',
    price: 80,
    discountedPrice: 70,
    unit: '250g',
    image: '🧄',
    rating: 4.4,
    reviews: 567,
    inStock: true,
    description: 'Fresh garlic bulbs',
    tags: ['fresh', 'vegetables', 'essential']
  },
  {
    id: 'fv-011',
    name: 'Ginger',
    brand: 'Farm Fresh',
    category: 'fruits-vegetables',
    subcategory: 'vegetables',
    price: 60,
    discountedPrice: 52,
    unit: '250g',
    image: '🫚',
    rating: 4.3,
    reviews: 423,
    inStock: true,
    description: 'Fresh ginger root',
    tags: ['fresh', 'vegetables', 'essential']
  },
  {
    id: 'fv-012',
    name: 'Watermelon',
    brand: 'Farm Fresh',
    category: 'fruits-vegetables',
    subcategory: 'fruits',
    price: 80,
    discountedPrice: 65,
    unit: '1 piece (~2kg)',
    image: '🍉',
    rating: 4.5,
    reviews: 289,
    inStock: true,
    description: 'Sweet and refreshing watermelon',
    tags: ['seasonal', 'fruits']
  },
  {
    id: 'fv-013',
    name: 'Cucumber',
    brand: 'Green Valley',
    category: 'fruits-vegetables',
    subcategory: 'vegetables',
    price: 25,
    discountedPrice: 20,
    unit: '500g',
    image: '🥒',
    rating: 4.2,
    reviews: 312,
    inStock: true,
    description: 'Fresh cucumbers, great for salads',
    tags: ['fresh', 'vegetables']
  },
  {
    id: 'fv-014',
    name: 'Lemon',
    brand: 'Farm Fresh',
    category: 'fruits-vegetables',
    subcategory: 'fruits',
    price: 30,
    discountedPrice: 25,
    unit: '6 pieces',
    image: '🍋',
    rating: 4.3,
    reviews: 456,
    inStock: true,
    description: 'Fresh lemons, tangy and juicy',
    tags: ['fresh', 'fruits', 'essential']
  },
  {
    id: 'fv-015',
    name: 'Broccoli',
    brand: 'Green Valley',
    category: 'fruits-vegetables',
    subcategory: 'vegetables',
    price: 65,
    discountedPrice: 55,
    unit: '500g',
    image: '🥦',
    rating: 4.4,
    reviews: 198,
    inStock: true,
    description: 'Fresh broccoli florets',
    tags: ['fresh', 'vegetables', 'healthy']
  },

  // ─── EGGS ──────────────────────────────────────────────────────────────────
  {
    id: 'eg-001',
    name: 'Farm Fresh Eggs',
    brand: 'Country Eggs',
    category: 'eggs',
    subcategory: 'eggs',
    price: 90,
    discountedPrice: 84,
    unit: '12 pieces',
    image: '🥚',
    rating: 4.7,
    reviews: 892,
    inStock: true,
    description: 'Fresh farm eggs, rich in protein',
    tags: ['eggs', 'protein', 'fresh']
  },
  {
    id: 'eg-002',
    name: 'Organic Brown Eggs',
    brand: 'Organic India',
    category: 'eggs',
    subcategory: 'eggs',
    price: 120,
    discountedPrice: 110,
    unit: '6 pieces',
    image: '🥚',
    rating: 4.8,
    reviews: 456,
    inStock: true,
    description: 'Free-range organic brown eggs',
    tags: ['eggs', 'organic', 'free-range']
  },
  {
    id: 'eg-003',
    name: 'White Eggs',
    brand: 'Suguna',
    category: 'eggs',
    subcategory: 'eggs',
    price: 75,
    discountedPrice: 70,
    unit: '12 pieces',
    image: '🥚',
    rating: 4.5,
    reviews: 678,
    inStock: true,
    description: 'Fresh white eggs from Suguna farms',
    tags: ['eggs', 'fresh', 'protein']
  },
  {
    id: 'eg-004',
    name: 'Desi Eggs',
    brand: 'Village Farm',
    category: 'eggs',
    subcategory: 'eggs',
    price: 150,
    discountedPrice: 135,
    unit: '12 pieces',
    image: '🥚',
    rating: 4.9,
    reviews: 345,
    inStock: true,
    description: 'Country desi eggs, naturally raised hens',
    tags: ['eggs', 'desi', 'natural']
  },
  {
    id: 'eg-005',
    name: 'Omega-3 Eggs',
    brand: 'Kegg Farms',
    category: 'eggs',
    subcategory: 'eggs',
    price: 180,
    discountedPrice: 165,
    unit: '6 pieces',
    image: '🥚',
    rating: 4.6,
    reviews: 234,
    inStock: true,
    description: 'Enriched with Omega-3 fatty acids',
    tags: ['eggs', 'omega-3', 'healthy']
  },

  // ─── MEAT ──────────────────────────────────────────────────────────────────
  {
    id: 'mt-001',
    name: 'Chicken Breast',
    brand: 'Licious',
    category: 'meat',
    subcategory: 'chicken',
    price: 299,
    discountedPrice: 269,
    unit: '500g',
    image: '🍗',
    rating: 4.6,
    reviews: 1234,
    inStock: true,
    description: 'Boneless chicken breast, cleaned and ready to cook',
    tags: ['chicken', 'meat', 'protein']
  },
  {
    id: 'mt-002',
    name: 'Chicken Curry Cut',
    brand: 'Licious',
    category: 'meat',
    subcategory: 'chicken',
    price: 249,
    discountedPrice: 229,
    unit: '500g',
    image: '🍗',
    rating: 4.5,
    reviews: 987,
    inStock: true,
    description: 'Fresh chicken pieces, perfect for curries',
    tags: ['chicken', 'meat', 'curry']
  },
  {
    id: 'mt-003',
    name: 'Mutton Curry Cut',
    brand: 'FreshToHome',
    category: 'meat',
    subcategory: 'mutton',
    price: 699,
    discountedPrice: 649,
    unit: '500g',
    image: '🥩',
    rating: 4.7,
    reviews: 567,
    inStock: true,
    description: 'Fresh mutton pieces, cleaned and cut',
    tags: ['mutton', 'meat', 'curry']
  },
  {
    id: 'mt-004',
    name: 'Fish Rohu',
    brand: 'FreshToHome',
    category: 'meat',
    subcategory: 'fish',
    price: 349,
    discountedPrice: 319,
    unit: '500g',
    image: '🐟',
    rating: 4.4,
    reviews: 456,
    inStock: true,
    description: 'Fresh Rohu fish, cleaned and cut',
    tags: ['fish', 'seafood', 'fresh']
  },
  {
    id: 'mt-005',
    name: 'Prawns',
    brand: 'Licious',
    category: 'meat',
    subcategory: 'seafood',
    price: 499,
    discountedPrice: 449,
    unit: '250g',
    image: '🦐',
    rating: 4.6,
    reviews: 345,
    inStock: true,
    description: 'Fresh cleaned prawns, deveined',
    tags: ['prawns', 'seafood', 'fresh']
  },
  {
    id: 'mt-006',
    name: 'Chicken Keema',
    brand: 'Licious',
    category: 'meat',
    subcategory: 'chicken',
    price: 279,
    discountedPrice: 249,
    unit: '500g',
    image: '🍗',
    rating: 4.5,
    reviews: 678,
    inStock: true,
    description: 'Minced chicken, perfect for kebabs and curries',
    tags: ['chicken', 'keema', 'meat']
  },
  {
    id: 'mt-007',
    name: 'Mutton Keema',
    brand: 'FreshToHome',
    category: 'meat',
    subcategory: 'mutton',
    price: 749,
    discountedPrice: 699,
    unit: '500g',
    image: '🥩',
    rating: 4.6,
    reviews: 389,
    inStock: true,
    description: 'Minced mutton for koftas and curries',
    tags: ['mutton', 'keema', 'meat']
  },
  {
    id: 'mt-008',
    name: 'Surmai Fish',
    brand: 'FreshToHome',
    category: 'meat',
    subcategory: 'fish',
    price: 599,
    discountedPrice: 549,
    unit: '500g',
    image: '🐟',
    rating: 4.7,
    reviews: 234,
    inStock: true,
    description: 'King fish (Surmai) steaks, fresh catch',
    tags: ['fish', 'surmai', 'seafood']
  },

  // ─── DAIRY & BREAKFAST (kept for internal use / TOP_ESSENTIALS) ────────────
  {
    id: 'db-001',
    name: 'Amul Full Cream Milk',
    brand: 'Amul',
    category: 'dairy-breakfast',
    subcategory: 'milk',
    price: 68,
    discountedPrice: 68,
    unit: '1L',
    image: '🥛',
    rating: 4.6,
    reviews: 1234,
    inStock: true,
    description: 'Fresh full cream milk from Amul',
    tags: ['dairy', 'milk', 'essential']
  },
  {
    id: 'db-002',
    name: 'Farm Fresh Eggs (Dairy)',
    brand: 'Country Eggs',
    category: 'dairy-breakfast',
    subcategory: 'eggs',
    price: 90,
    discountedPrice: 84,
    unit: '12 pieces',
    image: '🥚',
    rating: 4.7,
    reviews: 892,
    inStock: true,
    description: 'Fresh farm eggs, rich in protein',
    tags: ['eggs', 'protein', 'fresh']
  },
  {
    id: 'db-003',
    name: 'Amul Butter',
    brand: 'Amul',
    category: 'dairy-breakfast',
    subcategory: 'butter',
    price: 55,
    discountedPrice: 52,
    unit: '100g',
    image: '🧈',
    rating: 4.8,
    reviews: 2345,
    inStock: true,
    description: 'Creamy Amul butter, perfect for toast',
    tags: ['dairy', 'butter', 'amul']
  },
  {
    id: 'db-004',
    name: 'Britannia Cheese Slices',
    brand: 'Britannia',
    category: 'dairy-breakfast',
    subcategory: 'cheese',
    price: 120,
    discountedPrice: 108,
    unit: '200g',
    image: '🧀',
    rating: 4.5,
    reviews: 678,
    inStock: true,
    description: 'Processed cheese slices for sandwiches',
    tags: ['dairy', 'cheese', 'britannia']
  },
  {
    id: 'db-005',
    name: 'Epigamia Greek Yogurt',
    brand: 'Epigamia',
    category: 'dairy-breakfast',
    subcategory: 'yogurt',
    price: 85,
    discountedPrice: 75,
    unit: '400g',
    image: '🫙',
    rating: 4.6,
    reviews: 456,
    inStock: true,
    description: 'Thick and creamy Greek yogurt',
    tags: ['dairy', 'yogurt', 'healthy']
  },
  {
    id: 'db-006',
    name: "Kellogg's Corn Flakes",
    brand: "Kellogg's",
    category: 'dairy-breakfast',
    subcategory: 'cereals',
    price: 180,
    discountedPrice: 155,
    unit: '500g',
    image: '🥣',
    rating: 4.4,
    reviews: 789,
    inStock: true,
    description: 'Crispy corn flakes for a healthy breakfast',
    tags: ['breakfast', 'cereals', 'kelloggs']
  },
  {
    id: 'db-007',
    name: 'Britannia Brown Bread',
    brand: 'Britannia',
    category: 'dairy-breakfast',
    subcategory: 'bread',
    price: 45,
    discountedPrice: 42,
    unit: '400g',
    image: '🍞',
    rating: 4.3,
    reviews: 567,
    inStock: true,
    description: 'Whole wheat brown bread',
    tags: ['bread', 'breakfast', 'whole-wheat']
  },
  {
    id: 'db-008',
    name: 'Nandini Paneer',
    brand: 'Nandini',
    category: 'dairy-breakfast',
    subcategory: 'paneer',
    price: 95,
    discountedPrice: 88,
    unit: '200g',
    image: '🧀',
    rating: 4.5,
    reviews: 345,
    inStock: true,
    description: 'Fresh cottage cheese, perfect for curries',
    tags: ['dairy', 'paneer', 'fresh']
  },
  {
    id: 'db-009',
    name: 'Quaker Oats',
    brand: 'Quaker',
    category: 'dairy-breakfast',
    subcategory: 'cereals',
    price: 160,
    discountedPrice: 140,
    unit: '500g',
    image: '🥣',
    rating: 4.5,
    reviews: 678,
    inStock: true,
    description: 'Healthy rolled oats for breakfast',
    tags: ['breakfast', 'oats', 'healthy']
  },
  {
    id: 'db-010',
    name: 'Amul Dahi',
    brand: 'Amul',
    category: 'dairy-breakfast',
    subcategory: 'yogurt',
    price: 45,
    discountedPrice: 42,
    unit: '400g',
    image: '🫙',
    rating: 4.4,
    reviews: 890,
    inStock: true,
    description: 'Fresh curd from Amul',
    tags: ['dairy', 'curd', 'amul']
  },

  // ─── SNACKS ────────────────────────────────────────────────────────────────
  {
    id: 'sn-001',
    name: "Lay's Classic Salted",
    brand: "Lay's",
    category: 'snacks',
    subcategory: 'chips',
    price: 20,
    discountedPrice: 20,
    unit: '26g',
    image: '🥔',
    rating: 4.3,
    reviews: 2345,
    inStock: true,
    description: 'Classic salted potato chips',
    tags: ['chips', 'snacks', 'lays']
  },
  {
    id: 'sn-002',
    name: 'Parle-G Biscuits',
    brand: 'Parle',
    category: 'snacks',
    subcategory: 'biscuits',
    price: 10,
    discountedPrice: 10,
    unit: '100g',
    image: '🍪',
    rating: 4.7,
    reviews: 5678,
    inStock: true,
    description: "India's favourite glucose biscuits",
    tags: ['biscuits', 'snacks', 'parle']
  },
  {
    id: 'sn-003',
    name: 'Maggi 2-Minute Noodles',
    brand: 'Maggi',
    category: 'snacks',
    subcategory: 'instant-noodles',
    price: 14,
    discountedPrice: 14,
    unit: '70g',
    image: '🍜',
    rating: 4.6,
    reviews: 8901,
    inStock: true,
    description: 'Quick and tasty instant noodles',
    tags: ['noodles', 'instant', 'maggi']
  },
  {
    id: 'sn-004',
    name: "Haldiram's Bhujia",
    brand: "Haldiram's",
    category: 'snacks',
    subcategory: 'namkeen',
    price: 60,
    discountedPrice: 55,
    unit: '200g',
    image: '🥜',
    rating: 4.5,
    reviews: 1234,
    inStock: true,
    description: 'Crispy and spicy bhujia namkeen',
    tags: ['namkeen', 'snacks', 'haldirams']
  },
  {
    id: 'sn-005',
    name: 'Oreo Cookies',
    brand: 'Oreo',
    category: 'snacks',
    subcategory: 'cookies',
    price: 35,
    discountedPrice: 30,
    unit: '120g',
    image: '🍪',
    rating: 4.6,
    reviews: 3456,
    inStock: true,
    description: 'Classic chocolate sandwich cookies',
    tags: ['cookies', 'snacks', 'oreo']
  },
  {
    id: 'sn-006',
    name: 'Kurkure Masala Munch',
    brand: 'Kurkure',
    category: 'snacks',
    subcategory: 'chips',
    price: 20,
    discountedPrice: 20,
    unit: '90g',
    image: '🌽',
    rating: 4.4,
    reviews: 2345,
    inStock: true,
    description: 'Spicy and crunchy corn puffs',
    tags: ['chips', 'snacks', 'kurkure']
  },
  {
    id: 'sn-007',
    name: 'Cadbury Dairy Milk',
    brand: 'Cadbury',
    category: 'snacks',
    subcategory: 'chocolate',
    price: 40,
    discountedPrice: 38,
    unit: '45g',
    image: '🍫',
    rating: 4.8,
    reviews: 4567,
    inStock: true,
    description: 'Smooth and creamy milk chocolate',
    tags: ['chocolate', 'snacks', 'cadbury']
  },
  {
    id: 'sn-008',
    name: 'Tropicana Orange Juice',
    brand: 'Tropicana',
    category: 'snacks',
    subcategory: 'beverages',
    price: 99,
    discountedPrice: 89,
    unit: '1L',
    image: '🍊',
    rating: 4.3,
    reviews: 678,
    inStock: true,
    description: '100% pure orange juice',
    tags: ['juice', 'beverages', 'tropicana']
  },
  {
    id: 'sn-009',
    name: 'Bingo Mad Angles',
    brand: 'Bingo',
    category: 'snacks',
    subcategory: 'chips',
    price: 20,
    discountedPrice: 20,
    unit: '90g',
    image: '🔺',
    rating: 4.2,
    reviews: 1234,
    inStock: true,
    description: 'Triangular chips with masala flavour',
    tags: ['chips', 'snacks', 'bingo']
  },
  {
    id: 'sn-010',
    name: 'Britannia Good Day',
    brand: 'Britannia',
    category: 'snacks',
    subcategory: 'biscuits',
    price: 30,
    discountedPrice: 28,
    unit: '150g',
    image: '🍪',
    rating: 4.5,
    reviews: 2345,
    inStock: true,
    description: 'Butter cookies with cashew',
    tags: ['biscuits', 'snacks', 'britannia']
  },

  // ─── PERSONAL CARE ─────────────────────────────────────────────────────────
  {
    id: 'pc-001',
    name: 'Dove Body Wash',
    brand: 'Dove',
    category: 'personal-care',
    subcategory: 'bath',
    price: 299,
    discountedPrice: 249,
    unit: '500ml',
    image: '🧴',
    rating: 4.6,
    reviews: 1234,
    inStock: true,
    description: 'Moisturising body wash with 1/4 moisturising cream',
    tags: ['bath', 'personal-care', 'dove']
  },
  {
    id: 'pc-002',
    name: 'Head & Shoulders Shampoo',
    brand: 'Head & Shoulders',
    category: 'personal-care',
    subcategory: 'hair',
    price: 349,
    discountedPrice: 299,
    unit: '400ml',
    image: '🧴',
    rating: 4.5,
    reviews: 2345,
    inStock: true,
    description: 'Anti-dandruff shampoo for clean scalp',
    tags: ['hair', 'shampoo', 'personal-care']
  },
  {
    id: 'pc-003',
    name: 'Colgate MaxFresh',
    brand: 'Colgate',
    category: 'personal-care',
    subcategory: 'oral-care',
    price: 99,
    discountedPrice: 89,
    unit: '150g',
    image: '🦷',
    rating: 4.4,
    reviews: 3456,
    inStock: true,
    description: 'Cooling crystals toothpaste for fresh breath',
    tags: ['oral-care', 'toothpaste', 'colgate']
  },
  {
    id: 'pc-004',
    name: 'Nivea Body Lotion',
    brand: 'Nivea',
    category: 'personal-care',
    subcategory: 'skin-care',
    price: 249,
    discountedPrice: 199,
    unit: '400ml',
    image: '🧴',
    rating: 4.5,
    reviews: 1567,
    inStock: true,
    description: 'Deep moisture body lotion',
    tags: ['skin-care', 'lotion', 'nivea']
  },
  {
    id: 'pc-005',
    name: 'Gillette Mach3 Razor',
    brand: 'Gillette',
    category: 'personal-care',
    subcategory: 'shaving',
    price: 299,
    discountedPrice: 249,
    unit: '1 piece',
    image: '🪒',
    rating: 4.6,
    reviews: 890,
    inStock: true,
    description: '3-blade razor for a close shave',
    tags: ['shaving', 'razor', 'gillette']
  },
  {
    id: 'pc-006',
    name: 'Whisper Ultra Pads',
    brand: 'Whisper',
    category: 'personal-care',
    subcategory: 'feminine-care',
    price: 149,
    discountedPrice: 129,
    unit: '30 pads',
    image: '🩹',
    rating: 4.7,
    reviews: 2345,
    inStock: true,
    description: 'Ultra thin pads with wings',
    tags: ['feminine-care', 'personal-care', 'whisper']
  },
  {
    id: 'pc-007',
    name: 'Dettol Hand Sanitizer',
    brand: 'Dettol',
    category: 'personal-care',
    subcategory: 'hygiene',
    price: 99,
    discountedPrice: 85,
    unit: '200ml',
    image: '🧴',
    rating: 4.5,
    reviews: 1234,
    inStock: true,
    description: '99.9% germ protection hand sanitizer',
    tags: ['hygiene', 'sanitizer', 'dettol']
  },
  {
    id: 'pc-008',
    name: 'Pantene Pro-V Conditioner',
    brand: 'Pantene',
    category: 'personal-care',
    subcategory: 'hair',
    price: 249,
    discountedPrice: 219,
    unit: '340ml',
    image: '🧴',
    rating: 4.4,
    reviews: 678,
    inStock: true,
    description: 'Smooth and silky hair conditioner',
    tags: ['hair', 'conditioner', 'pantene']
  },

  // ─── PHARMACY ──────────────────────────────────────────────────────────────
  {
    id: 'ph-001',
    name: 'Dolo 650',
    brand: 'Micro Labs',
    category: 'pharmacy',
    subcategory: 'pain-relief',
    price: 30,
    discountedPrice: 28,
    unit: '15 tablets',
    image: '💊',
    rating: 4.8,
    reviews: 5678,
    inStock: true,
    description: 'Paracetamol 650mg for fever and pain',
    tags: ['medicine', 'fever', 'pain-relief']
  },
  {
    id: 'ph-002',
    name: 'Revital H Capsules',
    brand: 'Revital',
    category: 'pharmacy',
    subcategory: 'vitamins',
    price: 299,
    discountedPrice: 269,
    unit: '30 capsules',
    image: '💊',
    rating: 4.5,
    reviews: 1234,
    inStock: true,
    description: 'Daily multivitamin and mineral supplement',
    tags: ['vitamins', 'supplements', 'health']
  },
  {
    id: 'ph-003',
    name: 'Vicks VapoRub',
    brand: 'Vicks',
    category: 'pharmacy',
    subcategory: 'cold-cough',
    price: 99,
    discountedPrice: 89,
    unit: '50g',
    image: '🫙',
    rating: 4.7,
    reviews: 2345,
    inStock: true,
    description: 'Relief from cold, cough and blocked nose',
    tags: ['cold', 'cough', 'vicks']
  },
  {
    id: 'ph-004',
    name: 'Glucon-D Energy Drink',
    brand: 'Glucon-D',
    category: 'pharmacy',
    subcategory: 'energy',
    price: 120,
    discountedPrice: 105,
    unit: '500g',
    image: '🥤',
    rating: 4.4,
    reviews: 890,
    inStock: true,
    description: 'Instant energy glucose drink',
    tags: ['energy', 'glucose', 'health']
  },
  {
    id: 'ph-005',
    name: 'Band-Aid Strips',
    brand: 'Band-Aid',
    category: 'pharmacy',
    subcategory: 'first-aid',
    price: 75,
    discountedPrice: 65,
    unit: '20 strips',
    image: '🩹',
    rating: 4.5,
    reviews: 567,
    inStock: true,
    description: 'Flexible fabric bandage strips',
    tags: ['first-aid', 'bandage', 'health']
  },
  {
    id: 'ph-006',
    name: 'Himalaya Liv.52',
    brand: 'Himalaya',
    category: 'pharmacy',
    subcategory: 'liver-care',
    price: 135,
    discountedPrice: 120,
    unit: '100 tablets',
    image: '💊',
    rating: 4.6,
    reviews: 1234,
    inStock: true,
    description: 'Liver health supplement',
    tags: ['liver', 'health', 'himalaya']
  },

  // ─── HOUSEHOLD ─────────────────────────────────────────────────────────────
  {
    id: 'hh-001',
    name: 'Surf Excel Matic',
    brand: 'Surf Excel',
    category: 'household',
    subcategory: 'laundry',
    price: 299,
    discountedPrice: 269,
    unit: '1kg',
    image: '🧺',
    rating: 4.6,
    reviews: 2345,
    inStock: true,
    description: 'Front load washing machine detergent',
    tags: ['laundry', 'detergent', 'surf-excel']
  },
  {
    id: 'hh-002',
    name: 'Colin Glass Cleaner',
    brand: 'Colin',
    category: 'household',
    subcategory: 'cleaning',
    price: 99,
    discountedPrice: 89,
    unit: '500ml',
    image: '🧹',
    rating: 4.4,
    reviews: 678,
    inStock: true,
    description: 'Streak-free glass and surface cleaner',
    tags: ['cleaning', 'glass', 'colin']
  },
  {
    id: 'hh-003',
    name: 'Good Knight Mosquito Coil',
    brand: 'Good Knight',
    category: 'household',
    subcategory: 'pest-control',
    price: 45,
    discountedPrice: 40,
    unit: '10 coils',
    image: '🌀',
    rating: 4.3,
    reviews: 1234,
    inStock: true,
    description: 'Effective mosquito repellent coils',
    tags: ['pest-control', 'mosquito', 'good-knight']
  },
  {
    id: 'hh-004',
    name: 'Vim Dishwash Bar',
    brand: 'Vim',
    category: 'household',
    subcategory: 'kitchen',
    price: 30,
    discountedPrice: 28,
    unit: '200g',
    image: '🧽',
    rating: 4.5,
    reviews: 2345,
    inStock: true,
    description: 'Lemon dishwash bar for sparkling clean utensils',
    tags: ['kitchen', 'dishwash', 'vim']
  },
  {
    id: 'hh-005',
    name: 'Harpic Toilet Cleaner',
    brand: 'Harpic',
    category: 'household',
    subcategory: 'bathroom',
    price: 99,
    discountedPrice: 89,
    unit: '500ml',
    image: '🚽',
    rating: 4.4,
    reviews: 890,
    inStock: true,
    description: 'Powerful toilet bowl cleaner',
    tags: ['bathroom', 'toilet', 'harpic']
  },
  {
    id: 'hh-006',
    name: 'Scotch-Brite Scrub Pad',
    brand: 'Scotch-Brite',
    category: 'household',
    subcategory: 'kitchen',
    price: 45,
    discountedPrice: 40,
    unit: '3 pieces',
    image: '🧽',
    rating: 4.5,
    reviews: 1234,
    inStock: true,
    description: 'Heavy duty scrubbing pads',
    tags: ['kitchen', 'scrub', 'scotch-brite']
  },
  {
    id: 'hh-007',
    name: 'Ariel Washing Powder',
    brand: 'Ariel',
    category: 'household',
    subcategory: 'laundry',
    price: 249,
    discountedPrice: 219,
    unit: '1kg',
    image: '🧺',
    rating: 4.5,
    reviews: 1567,
    inStock: true,
    description: 'Advanced stain removal washing powder',
    tags: ['laundry', 'detergent', 'ariel']
  },
  {
    id: 'hh-008',
    name: 'Lizol Floor Cleaner',
    brand: 'Lizol',
    category: 'household',
    subcategory: 'cleaning',
    price: 149,
    discountedPrice: 129,
    unit: '500ml',
    image: '🧹',
    rating: 4.4,
    reviews: 890,
    inStock: true,
    description: 'Disinfectant floor cleaner',
    tags: ['cleaning', 'floor', 'lizol']
  },

  // ─── ELECTRONICS ───────────────────────────────────────────────────────────
  {
    id: 'el-001',
    name: 'Duracell AA Batteries',
    brand: 'Duracell',
    category: 'electronics',
    subcategory: 'batteries',
    price: 199,
    discountedPrice: 179,
    unit: '4 pieces',
    image: '🔋',
    rating: 4.6,
    reviews: 1234,
    inStock: true,
    description: 'Long-lasting alkaline batteries',
    tags: ['batteries', 'electronics', 'duracell']
  },
  {
    id: 'el-002',
    name: 'Syska LED Bulb',
    brand: 'Syska',
    category: 'electronics',
    subcategory: 'lighting',
    price: 149,
    discountedPrice: 129,
    unit: '9W',
    image: '💡',
    rating: 4.4,
    reviews: 890,
    inStock: true,
    description: 'Energy-saving LED bulb',
    tags: ['lighting', 'led', 'syska']
  },
  {
    id: 'el-003',
    name: 'Portronics USB Cable',
    brand: 'Portronics',
    category: 'electronics',
    subcategory: 'accessories',
    price: 299,
    discountedPrice: 249,
    unit: '1m',
    image: '🔌',
    rating: 4.3,
    reviews: 567,
    inStock: true,
    description: 'Fast charging USB-C cable',
    tags: ['cable', 'charging', 'electronics']
  },
  {
    id: 'el-004',
    name: 'Boat Earphones',
    brand: 'Boat',
    category: 'electronics',
    subcategory: 'audio',
    price: 599,
    discountedPrice: 499,
    unit: '1 piece',
    image: '🎧',
    rating: 4.2,
    reviews: 2345,
    inStock: true,
    description: 'Wired earphones with mic',
    tags: ['audio', 'earphones', 'boat']
  },
  {
    id: 'el-005',
    name: 'Ambrane Power Bank',
    brand: 'Ambrane',
    category: 'electronics',
    subcategory: 'power',
    price: 999,
    discountedPrice: 849,
    unit: '10000mAh',
    image: '🔋',
    rating: 4.3,
    reviews: 1234,
    inStock: true,
    description: 'Compact power bank for on-the-go charging',
    tags: ['power-bank', 'charging', 'electronics']
  },

  // ─── PET SUPPLIES ──────────────────────────────────────────────────────────
  {
    id: 'ps-001',
    name: 'Pedigree Adult Dog Food',
    brand: 'Pedigree',
    category: 'pet-supplies',
    subcategory: 'dog-food',
    price: 399,
    discountedPrice: 349,
    unit: '1.2kg',
    image: '🐕',
    rating: 4.5,
    reviews: 678,
    inStock: true,
    description: 'Complete nutrition for adult dogs',
    tags: ['dog-food', 'pet', 'pedigree']
  },
  {
    id: 'ps-002',
    name: 'Whiskas Cat Food',
    brand: 'Whiskas',
    category: 'pet-supplies',
    subcategory: 'cat-food',
    price: 299,
    discountedPrice: 269,
    unit: '1.2kg',
    image: '🐈',
    rating: 4.4,
    reviews: 456,
    inStock: true,
    description: 'Balanced nutrition for adult cats',
    tags: ['cat-food', 'pet', 'whiskas']
  },
  {
    id: 'ps-003',
    name: 'Himalaya Pet Shampoo',
    brand: 'Himalaya',
    category: 'pet-supplies',
    subcategory: 'grooming',
    price: 199,
    discountedPrice: 179,
    unit: '200ml',
    image: '🐾',
    rating: 4.3,
    reviews: 234,
    inStock: true,
    description: 'Gentle shampoo for dogs and cats',
    tags: ['grooming', 'pet', 'himalaya']
  },
  {
    id: 'ps-004',
    name: 'Drools Dog Treats',
    brand: 'Drools',
    category: 'pet-supplies',
    subcategory: 'treats',
    price: 149,
    discountedPrice: 129,
    unit: '100g',
    image: '🦴',
    rating: 4.5,
    reviews: 345,
    inStock: true,
    description: 'Tasty treats for training and rewarding',
    tags: ['treats', 'dog', 'drools']
  }
];

export const TOP_ESSENTIALS: Product[] = [
  ALL_PRODUCTS.find(p => p.id === 'fv-001')!, // Tomatoes
  ALL_PRODUCTS.find(p => p.id === 'eg-001')!, // Eggs
  ALL_PRODUCTS.find(p => p.id === 'fv-007')!, // Potatoes
  ALL_PRODUCTS.find(p => p.id === 'mt-001')!, // Chicken Breast
  ALL_PRODUCTS.find(p => p.id === 'fv-004')!, // Bananas
  ALL_PRODUCTS.find(p => p.id === 'mt-003')!, // Mutton
  ALL_PRODUCTS.find(p => p.id === 'eg-002')!, // Organic Brown Eggs
  ALL_PRODUCTS.find(p => p.id === 'fv-005')!, // Onions
];
